# Generated by Django 5.0.6 on 2024-06-05 19:35
from __future__ import annotations

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="GristColumn",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("col_id", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("attachments", "Attachments"),
                            ("boolean", "Bool"),
                            ("date", "Date"),
                            ("integer", "Int"),
                            ("numeric", "Numeric"),
                            ("text", "Text"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grist column",
                "verbose_name_plural": "Grist columns",
                "db_table": "gristcolumn",
                "ordering": ("col_id",),
            },
        ),
        migrations.AlterField(
            model_name="gristconfig",
            name="object_type",
            field=models.CharField(
                choices=[("projects.Project", "Project"), ("survey.Answer", "Answer")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="object_type",
            field=models.CharField(
                choices=[("projects.Project", "Project"), ("survey.Answer", "Answer")],
                help_text="Type of the object that triggered the webhook event",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="gristconfig",
            name="table_columns",
            field=models.ManyToManyField(related_name="grist_configs", to="main.gristcolumn"),
        ),
    ]
