# Generated by Django 5.0.6 on 2024-06-05 20:03
from __future__ import annotations

import functools

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_gristcolumn_alter_gristconfig_object_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gristconfig",
            name="columns",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=functools.partial(
                    django.core.serializers.json.DjangoJSONEncoder,
                    *(),
                    **{"indent": 2, "sort_keys": True},
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gristconfig",
            name="object_type",
            field=models.CharField(
                choices=[("projects.Project", "Project"), ("survey.Answer", "Answer")],
                default="projects.Project",
                max_length=32,
            ),
        ),
    ]
