name: "Check, test and deploy to Clevercloud"
on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/run_check.yml

  test:
    uses: ./.github/workflows/run_tests.yml

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Clevercloud
        uses: 47ng/actions-clever-cloud@v2.0.0
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
